//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_DiscountInformation_Discounts", "Discounts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShoppingWebSite.Access_Data.Discount), "DiscountInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShoppingWebSite.Access_Data.DiscountItem), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_DiscountInformation_Products", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShoppingWebSite.Access_Data.Product), "DiscountInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShoppingWebSite.Access_Data.DiscountItem), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Reviews_Products", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShoppingWebSite.Access_Data.Product), "Reviews", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShoppingWebSite.Access_Data.Review), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Reviews_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShoppingWebSite.Access_Data.User), "Reviews", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShoppingWebSite.Access_Data.Review), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Suggestions_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NFCShoppingWebSite.Access_Data.User), "Suggestions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShoppingWebSite.Access_Data.Suggestion), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_SecCategories_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShoppingWebSite.Access_Data.Category), "SecCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShoppingWebSite.Access_Data.SecCategory), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Products_SecCategories", "SecCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShoppingWebSite.Access_Data.SecCategory), "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShoppingWebSite.Access_Data.Product), true)]

#endregion

namespace NFCShoppingWebSite.Access_Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ShopEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ShopEntities object using the connection string found in the 'ShopEntities' section of the application configuration file.
        /// </summary>
        public ShopEntities() : base("name=ShopEntities", "ShopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShopEntities object.
        /// </summary>
        public ShopEntities(string connectionString) : base(connectionString, "ShopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShopEntities object.
        /// </summary>
        public ShopEntities(EntityConnection connection) : base(connection, "ShopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DiscountItem> DiscountItems
        {
            get
            {
                if ((_DiscountItems == null))
                {
                    _DiscountItems = base.CreateObjectSet<DiscountItem>("DiscountItems");
                }
                return _DiscountItems;
            }
        }
        private ObjectSet<DiscountItem> _DiscountItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Discount> Discounts
        {
            get
            {
                if ((_Discounts == null))
                {
                    _Discounts = base.CreateObjectSet<Discount>("Discounts");
                }
                return _Discounts;
            }
        }
        private ObjectSet<Discount> _Discounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Review> Reviews
        {
            get
            {
                if ((_Reviews == null))
                {
                    _Reviews = base.CreateObjectSet<Review>("Reviews");
                }
                return _Reviews;
            }
        }
        private ObjectSet<Review> _Reviews;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Suggestion> Suggestions
        {
            get
            {
                if ((_Suggestions == null))
                {
                    _Suggestions = base.CreateObjectSet<Suggestion>("Suggestions");
                }
                return _Suggestions;
            }
        }
        private ObjectSet<Suggestion> _Suggestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecCategory> SecCategories
        {
            get
            {
                if ((_SecCategories == null))
                {
                    _SecCategories = base.CreateObjectSet<SecCategory>("SecCategories");
                }
                return _SecCategories;
            }
        }
        private ObjectSet<SecCategory> _SecCategories;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DiscountItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDiscountItems(DiscountItem discountItem)
        {
            base.AddObject("DiscountItems", discountItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Discounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDiscounts(Discount discount)
        {
            base.AddObject("Discounts", discount);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Suggestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSuggestions(Suggestion suggestion)
        {
            base.AddObject("Suggestions", suggestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecCategories(SecCategory secCategory)
        {
            base.AddObject("SecCategories", secCategory);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of the categoryID property.</param>
        /// <param name="categoryName">Initial value of the categoryName property.</param>
        public static Category CreateCategory(global::System.Int32 categoryID, global::System.String categoryName)
        {
            Category category = new Category();
            category.categoryID = categoryID;
            category.categoryName = categoryName;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 categoryID
        {
            get
            {
                return _categoryID;
            }
            set
            {
                if (_categoryID != value)
                {
                    OncategoryIDChanging(value);
                    ReportPropertyChanging("categoryID");
                    _categoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("categoryID");
                    OncategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _categoryID;
        partial void OncategoryIDChanging(global::System.Int32 value);
        partial void OncategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categoryName
        {
            get
            {
                return _categoryName;
            }
            set
            {
                OncategoryNameChanging(value);
                ReportPropertyChanging("categoryName");
                _categoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("categoryName");
                OncategoryNameChanged();
            }
        }
        private global::System.String _categoryName;
        partial void OncategoryNameChanging(global::System.String value);
        partial void OncategoryNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_SecCategories_Categories", "SecCategory")]
        public EntityCollection<SecCategory> SecCategories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SecCategory>("Sys_DBModel.FK_SecCategories_Categories", "SecCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SecCategory>("Sys_DBModel.FK_SecCategories_Categories", "SecCategory", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Discount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Discount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Discount object.
        /// </summary>
        /// <param name="discountID">Initial value of the discountID property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="createdAt">Initial value of the createdAt property.</param>
        public static Discount CreateDiscount(global::System.Int32 discountID, global::System.String description, global::System.DateTime createdAt)
        {
            Discount discount = new Discount();
            discount.discountID = discountID;
            discount.description = description;
            discount.createdAt = createdAt;
            return discount;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 discountID
        {
            get
            {
                return _discountID;
            }
            set
            {
                if (_discountID != value)
                {
                    OndiscountIDChanging(value);
                    ReportPropertyChanging("discountID");
                    _discountID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("discountID");
                    OndiscountIDChanged();
                }
            }
        }
        private global::System.Int32 _discountID;
        partial void OndiscountIDChanging(global::System.Int32 value);
        partial void OndiscountIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createdAt
        {
            get
            {
                return _createdAt;
            }
            set
            {
                OncreatedAtChanging(value);
                ReportPropertyChanging("createdAt");
                _createdAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdAt");
                OncreatedAtChanged();
            }
        }
        private global::System.DateTime _createdAt;
        partial void OncreatedAtChanging(global::System.DateTime value);
        partial void OncreatedAtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_DiscountInformation_Discounts", "DiscountInformation")]
        public EntityCollection<DiscountItem> DiscountItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DiscountItem>("Sys_DBModel.FK_DiscountInformation_Discounts", "DiscountInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DiscountItem>("Sys_DBModel.FK_DiscountInformation_Discounts", "DiscountInformation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="DiscountItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DiscountItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DiscountItem object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="discountID">Initial value of the discountID property.</param>
        /// <param name="productID">Initial value of the productID property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="startDate">Initial value of the startDate property.</param>
        /// <param name="endDate">Initial value of the endDate property.</param>
        public static DiscountItem CreateDiscountItem(global::System.Int32 id, global::System.Int32 discountID, global::System.Int32 productID, global::System.String description, global::System.DateTime startDate, global::System.DateTime endDate)
        {
            DiscountItem discountItem = new DiscountItem();
            discountItem.id = id;
            discountItem.discountID = discountID;
            discountItem.productID = productID;
            discountItem.description = description;
            discountItem.startDate = startDate;
            discountItem.endDate = endDate;
            return discountItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 discountID
        {
            get
            {
                return _discountID;
            }
            set
            {
                OndiscountIDChanging(value);
                ReportPropertyChanging("discountID");
                _discountID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("discountID");
                OndiscountIDChanged();
            }
        }
        private global::System.Int32 _discountID;
        partial void OndiscountIDChanging(global::System.Int32 value);
        partial void OndiscountIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                OnproductIDChanging(value);
                ReportPropertyChanging("productID");
                _productID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productID");
                OnproductIDChanged();
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime startDate
        {
            get
            {
                return _startDate;
            }
            set
            {
                OnstartDateChanging(value);
                ReportPropertyChanging("startDate");
                _startDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startDate");
                OnstartDateChanged();
            }
        }
        private global::System.DateTime _startDate;
        partial void OnstartDateChanging(global::System.DateTime value);
        partial void OnstartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime endDate
        {
            get
            {
                return _endDate;
            }
            set
            {
                OnendDateChanging(value);
                ReportPropertyChanging("endDate");
                _endDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("endDate");
                OnendDateChanged();
            }
        }
        private global::System.DateTime _endDate;
        partial void OnendDateChanging(global::System.DateTime value);
        partial void OnendDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_DiscountInformation_Discounts", "Discounts")]
        public Discount Discount
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Discount>("Sys_DBModel.FK_DiscountInformation_Discounts", "Discounts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Discount>("Sys_DBModel.FK_DiscountInformation_Discounts", "Discounts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Discount> DiscountReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Discount>("Sys_DBModel.FK_DiscountInformation_Discounts", "Discounts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Discount>("Sys_DBModel.FK_DiscountInformation_Discounts", "Discounts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_DiscountInformation_Products", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_DiscountInformation_Products", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_DiscountInformation_Products", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_DiscountInformation_Products", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Sys_DBModel.FK_DiscountInformation_Products", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of the productID property.</param>
        /// <param name="secCategoryID">Initial value of the secCategoryID property.</param>
        /// <param name="barCode">Initial value of the barCode property.</param>
        /// <param name="productName">Initial value of the productName property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="description">Initial value of the description property.</param>
        public static Product CreateProduct(global::System.Int32 productID, global::System.Int32 secCategoryID, global::System.String barCode, global::System.String productName, global::System.Decimal price, global::System.String description)
        {
            Product product = new Product();
            product.productID = productID;
            product.secCategoryID = secCategoryID;
            product.barCode = barCode;
            product.productName = productName;
            product.price = price;
            product.description = description;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                if (_productID != value)
                {
                    OnproductIDChanging(value);
                    ReportPropertyChanging("productID");
                    _productID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("productID");
                    OnproductIDChanged();
                }
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 secCategoryID
        {
            get
            {
                return _secCategoryID;
            }
            set
            {
                OnsecCategoryIDChanging(value);
                ReportPropertyChanging("secCategoryID");
                _secCategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("secCategoryID");
                OnsecCategoryIDChanged();
            }
        }
        private global::System.Int32 _secCategoryID;
        partial void OnsecCategoryIDChanging(global::System.Int32 value);
        partial void OnsecCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String barCode
        {
            get
            {
                return _barCode;
            }
            set
            {
                OnbarCodeChanging(value);
                ReportPropertyChanging("barCode");
                _barCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("barCode");
                OnbarCodeChanged();
            }
        }
        private global::System.String _barCode;
        partial void OnbarCodeChanging(global::System.String value);
        partial void OnbarCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String productName
        {
            get
            {
                return _productName;
            }
            set
            {
                OnproductNameChanging(value);
                ReportPropertyChanging("productName");
                _productName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("productName");
                OnproductNameChanged();
            }
        }
        private global::System.String _productName;
        partial void OnproductNameChanging(global::System.String value);
        partial void OnproductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String brand
        {
            get
            {
                return _brand;
            }
            set
            {
                OnbrandChanging(value);
                ReportPropertyChanging("brand");
                _brand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("brand");
                OnbrandChanged();
            }
        }
        private global::System.String _brand;
        partial void OnbrandChanging(global::System.String value);
        partial void OnbrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String impageURL
        {
            get
            {
                return _impageURL;
            }
            set
            {
                OnimpageURLChanging(value);
                ReportPropertyChanging("impageURL");
                _impageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("impageURL");
                OnimpageURLChanged();
            }
        }
        private global::System.String _impageURL;
        partial void OnimpageURLChanging(global::System.String value);
        partial void OnimpageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_DiscountInformation_Products", "DiscountInformation")]
        public EntityCollection<DiscountItem> DiscountInformations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DiscountItem>("Sys_DBModel.FK_DiscountInformation_Products", "DiscountInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DiscountItem>("Sys_DBModel.FK_DiscountInformation_Products", "DiscountInformation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Reviews_Products", "Reviews")]
        public EntityCollection<Review> Reviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Review>("Sys_DBModel.FK_Reviews_Products", "Reviews");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Review>("Sys_DBModel.FK_Reviews_Products", "Reviews", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Products_SecCategories", "SecCategory")]
        public SecCategory SecCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecCategory>("Sys_DBModel.FK_Products_SecCategories", "SecCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecCategory>("Sys_DBModel.FK_Products_SecCategories", "SecCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SecCategory> SecCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecCategory>("Sys_DBModel.FK_Products_SecCategories", "SecCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SecCategory>("Sys_DBModel.FK_Products_SecCategories", "SecCategory", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Review")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Review : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="reviewID">Initial value of the reviewID property.</param>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="productID">Initial value of the productID property.</param>
        /// <param name="comment">Initial value of the comment property.</param>
        /// <param name="rating">Initial value of the rating property.</param>
        public static Review CreateReview(global::System.Int32 reviewID, global::System.Int32 userID, global::System.Int32 productID, global::System.String comment, global::System.Int16 rating)
        {
            Review review = new Review();
            review.reviewID = reviewID;
            review.userID = userID;
            review.productID = productID;
            review.comment = comment;
            review.rating = rating;
            return review;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 reviewID
        {
            get
            {
                return _reviewID;
            }
            set
            {
                if (_reviewID != value)
                {
                    OnreviewIDChanging(value);
                    ReportPropertyChanging("reviewID");
                    _reviewID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("reviewID");
                    OnreviewIDChanged();
                }
            }
        }
        private global::System.Int32 _reviewID;
        partial void OnreviewIDChanging(global::System.Int32 value);
        partial void OnreviewIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                OnproductIDChanging(value);
                ReportPropertyChanging("productID");
                _productID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productID");
                OnproductIDChanged();
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comment
        {
            get
            {
                return _comment;
            }
            set
            {
                OncommentChanging(value);
                ReportPropertyChanging("comment");
                _comment = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comment");
                OncommentChanged();
            }
        }
        private global::System.String _comment;
        partial void OncommentChanging(global::System.String value);
        partial void OncommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 rating
        {
            get
            {
                return _rating;
            }
            set
            {
                OnratingChanging(value);
                ReportPropertyChanging("rating");
                _rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rating");
                OnratingChanged();
            }
        }
        private global::System.Int16 _rating;
        partial void OnratingChanging(global::System.Int16 value);
        partial void OnratingChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Reviews_Products", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Reviews_Products", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Reviews_Products", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Reviews_Products", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Sys_DBModel.FK_Reviews_Products", "Products", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Reviews_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Reviews_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Reviews_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Reviews_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Sys_DBModel.FK_Reviews_Users", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="SecCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecCategory object.
        /// </summary>
        /// <param name="secCategoryID">Initial value of the secCategoryID property.</param>
        /// <param name="categoryID">Initial value of the categoryID property.</param>
        /// <param name="secCategoryName">Initial value of the secCategoryName property.</param>
        public static SecCategory CreateSecCategory(global::System.Int32 secCategoryID, global::System.Int32 categoryID, global::System.String secCategoryName)
        {
            SecCategory secCategory = new SecCategory();
            secCategory.secCategoryID = secCategoryID;
            secCategory.categoryID = categoryID;
            secCategory.secCategoryName = secCategoryName;
            return secCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 secCategoryID
        {
            get
            {
                return _secCategoryID;
            }
            set
            {
                if (_secCategoryID != value)
                {
                    OnsecCategoryIDChanging(value);
                    ReportPropertyChanging("secCategoryID");
                    _secCategoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("secCategoryID");
                    OnsecCategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _secCategoryID;
        partial void OnsecCategoryIDChanging(global::System.Int32 value);
        partial void OnsecCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 categoryID
        {
            get
            {
                return _categoryID;
            }
            set
            {
                OncategoryIDChanging(value);
                ReportPropertyChanging("categoryID");
                _categoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("categoryID");
                OncategoryIDChanged();
            }
        }
        private global::System.Int32 _categoryID;
        partial void OncategoryIDChanging(global::System.Int32 value);
        partial void OncategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String secCategoryName
        {
            get
            {
                return _secCategoryName;
            }
            set
            {
                OnsecCategoryNameChanging(value);
                ReportPropertyChanging("secCategoryName");
                _secCategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("secCategoryName");
                OnsecCategoryNameChanged();
            }
        }
        private global::System.String _secCategoryName;
        partial void OnsecCategoryNameChanging(global::System.String value);
        partial void OnsecCategoryNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_SecCategories_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Sys_DBModel.FK_SecCategories_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Sys_DBModel.FK_SecCategories_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Sys_DBModel.FK_SecCategories_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("Sys_DBModel.FK_SecCategories_Categories", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Products_SecCategories", "Product")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("Sys_DBModel.FK_Products_SecCategories", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("Sys_DBModel.FK_Products_SecCategories", "Product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Suggestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Suggestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Suggestion object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static Suggestion CreateSuggestion(global::System.Int32 id, global::System.String description, global::System.DateTime date)
        {
            Suggestion suggestion = new Suggestion();
            suggestion.id = id;
            suggestion.description = description;
            suggestion.date = date;
            return suggestion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userID;
        partial void OnuserIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Suggestions_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Suggestions_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Suggestions_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Suggestions_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Sys_DBModel.FK_Suggestions_Users", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="userName">Initial value of the userName property.</param>
        /// <param name="userPassword">Initial value of the userPassword property.</param>
        /// <param name="visitedTimes">Initial value of the visitedTimes property.</param>
        /// <param name="lastVisitedDate">Initial value of the lastVisitedDate property.</param>
        public static User CreateUser(global::System.Int32 userID, global::System.String userName, global::System.String userPassword, global::System.Int32 visitedTimes, global::System.DateTime lastVisitedDate)
        {
            User user = new User();
            user.userID = userID;
            user.userName = userName;
            user.userPassword = userPassword;
            user.visitedTimes = visitedTimes;
            user.lastVisitedDate = lastVisitedDate;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userPassword
        {
            get
            {
                return _userPassword;
            }
            set
            {
                OnuserPasswordChanging(value);
                ReportPropertyChanging("userPassword");
                _userPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userPassword");
                OnuserPasswordChanged();
            }
        }
        private global::System.String _userPassword;
        partial void OnuserPasswordChanging(global::System.String value);
        partial void OnuserPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private Nullable<global::System.Int32> _gender;
        partial void OngenderChanging(Nullable<global::System.Int32> value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 visitedTimes
        {
            get
            {
                return _visitedTimes;
            }
            set
            {
                OnvisitedTimesChanging(value);
                ReportPropertyChanging("visitedTimes");
                _visitedTimes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("visitedTimes");
                OnvisitedTimesChanged();
            }
        }
        private global::System.Int32 _visitedTimes;
        partial void OnvisitedTimesChanging(global::System.Int32 value);
        partial void OnvisitedTimesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime lastVisitedDate
        {
            get
            {
                return _lastVisitedDate;
            }
            set
            {
                OnlastVisitedDateChanging(value);
                ReportPropertyChanging("lastVisitedDate");
                _lastVisitedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastVisitedDate");
                OnlastVisitedDateChanged();
            }
        }
        private global::System.DateTime _lastVisitedDate;
        partial void OnlastVisitedDateChanging(global::System.DateTime value);
        partial void OnlastVisitedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Reviews_Users", "Reviews")]
        public EntityCollection<Review> Reviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Review>("Sys_DBModel.FK_Reviews_Users", "Reviews");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Review>("Sys_DBModel.FK_Reviews_Users", "Reviews", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Suggestions_Users", "Suggestions")]
        public EntityCollection<Suggestion> Suggestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Suggestion>("Sys_DBModel.FK_Suggestions_Users", "Suggestions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Suggestion>("Sys_DBModel.FK_Suggestions_Users", "Suggestions", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
