//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_SecCategories_Categories", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShopping_WebSite.Data_Access.Category), "SecCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShopping_WebSite.Data_Access.SecCategory), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_DiscountInformation_Products", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShopping_WebSite.Data_Access.Product), "DiscountInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShopping_WebSite.Data_Access.DiscountInformation), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Fan_Products", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShopping_WebSite.Data_Access.Product), "Fan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShopping_WebSite.Data_Access.Fan), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Food_Products", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShopping_WebSite.Data_Access.Product), "Food", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShopping_WebSite.Data_Access.Food), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Products_SecCategories", "SecCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShopping_WebSite.Data_Access.SecCategory), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShopping_WebSite.Data_Access.Product), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Reviews_Products", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShopping_WebSite.Data_Access.Product), "Reviews", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShopping_WebSite.Data_Access.Review), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_RiceCooker_Products", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShopping_WebSite.Data_Access.Product), "RiceCooker", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShopping_WebSite.Data_Access.RiceCooker), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Reviews_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NFCShopping_WebSite.Data_Access.User), "Reviews", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShopping_WebSite.Data_Access.Review), true)]
[assembly: EdmRelationshipAttribute("Sys_DBModel", "FK_Suggestions_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NFCShopping_WebSite.Data_Access.User), "Suggestions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NFCShopping_WebSite.Data_Access.Suggestion), true)]

#endregion

namespace NFCShopping_WebSite.Data_Access
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Sys_DBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Sys_DBEntities object using the connection string found in the 'Sys_DBEntities' section of the application configuration file.
        /// </summary>
        public Sys_DBEntities() : base("name=Sys_DBEntities", "Sys_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Sys_DBEntities object.
        /// </summary>
        public Sys_DBEntities(string connectionString) : base(connectionString, "Sys_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Sys_DBEntities object.
        /// </summary>
        public Sys_DBEntities(EntityConnection connection) : base(connection, "Sys_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DiscountInformation> DiscountInformations
        {
            get
            {
                if ((_DiscountInformations == null))
                {
                    _DiscountInformations = base.CreateObjectSet<DiscountInformation>("DiscountInformations");
                }
                return _DiscountInformations;
            }
        }
        private ObjectSet<DiscountInformation> _DiscountInformations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Fan> Fans
        {
            get
            {
                if ((_Fans == null))
                {
                    _Fans = base.CreateObjectSet<Fan>("Fans");
                }
                return _Fans;
            }
        }
        private ObjectSet<Fan> _Fans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Food> Foods
        {
            get
            {
                if ((_Foods == null))
                {
                    _Foods = base.CreateObjectSet<Food>("Foods");
                }
                return _Foods;
            }
        }
        private ObjectSet<Food> _Foods;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Review> Reviews
        {
            get
            {
                if ((_Reviews == null))
                {
                    _Reviews = base.CreateObjectSet<Review>("Reviews");
                }
                return _Reviews;
            }
        }
        private ObjectSet<Review> _Reviews;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RiceCooker> RiceCookers
        {
            get
            {
                if ((_RiceCookers == null))
                {
                    _RiceCookers = base.CreateObjectSet<RiceCooker>("RiceCookers");
                }
                return _RiceCookers;
            }
        }
        private ObjectSet<RiceCooker> _RiceCookers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecCategory> SecCategories
        {
            get
            {
                if ((_SecCategories == null))
                {
                    _SecCategories = base.CreateObjectSet<SecCategory>("SecCategories");
                }
                return _SecCategories;
            }
        }
        private ObjectSet<SecCategory> _SecCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Suggestion> Suggestions
        {
            get
            {
                if ((_Suggestions == null))
                {
                    _Suggestions = base.CreateObjectSet<Suggestion>("Suggestions");
                }
                return _Suggestions;
            }
        }
        private ObjectSet<Suggestion> _Suggestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DiscountInformations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDiscountInformations(DiscountInformation discountInformation)
        {
            base.AddObject("DiscountInformations", discountInformation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Fans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFans(Fan fan)
        {
            base.AddObject("Fans", fan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Foods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoods(Food food)
        {
            base.AddObject("Foods", food);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RiceCookers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRiceCookers(RiceCooker riceCooker)
        {
            base.AddObject("RiceCookers", riceCooker);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecCategories(SecCategory secCategory)
        {
            base.AddObject("SecCategories", secCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Suggestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSuggestions(Suggestion suggestion)
        {
            base.AddObject("Suggestions", suggestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of the categoryID property.</param>
        /// <param name="categoryName">Initial value of the categoryName property.</param>
        public static Category CreateCategory(global::System.Int32 categoryID, global::System.String categoryName)
        {
            Category category = new Category();
            category.categoryID = categoryID;
            category.categoryName = categoryName;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 categoryID
        {
            get
            {
                return _categoryID;
            }
            set
            {
                if (_categoryID != value)
                {
                    OncategoryIDChanging(value);
                    ReportPropertyChanging("categoryID");
                    _categoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("categoryID");
                    OncategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _categoryID;
        partial void OncategoryIDChanging(global::System.Int32 value);
        partial void OncategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categoryName
        {
            get
            {
                return _categoryName;
            }
            set
            {
                OncategoryNameChanging(value);
                ReportPropertyChanging("categoryName");
                _categoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("categoryName");
                OncategoryNameChanged();
            }
        }
        private global::System.String _categoryName;
        partial void OncategoryNameChanging(global::System.String value);
        partial void OncategoryNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_SecCategories_Categories", "SecCategories")]
        public EntityCollection<SecCategory> SecCategories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SecCategory>("Sys_DBModel.FK_SecCategories_Categories", "SecCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SecCategory>("Sys_DBModel.FK_SecCategories_Categories", "SecCategories", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="DiscountInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DiscountInformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DiscountInformation object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="productID">Initial value of the productID property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="imageURL">Initial value of the imageURL property.</param>
        /// <param name="startDate">Initial value of the startDate property.</param>
        /// <param name="endDate">Initial value of the endDate property.</param>
        public static DiscountInformation CreateDiscountInformation(global::System.Int32 id, global::System.Int32 productID, global::System.String description, global::System.String imageURL, global::System.DateTime startDate, global::System.DateTime endDate)
        {
            DiscountInformation discountInformation = new DiscountInformation();
            discountInformation.id = id;
            discountInformation.productID = productID;
            discountInformation.description = description;
            discountInformation.imageURL = imageURL;
            discountInformation.startDate = startDate;
            discountInformation.endDate = endDate;
            return discountInformation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                OnproductIDChanging(value);
                ReportPropertyChanging("productID");
                _productID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productID");
                OnproductIDChanged();
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imageURL
        {
            get
            {
                return _imageURL;
            }
            set
            {
                OnimageURLChanging(value);
                ReportPropertyChanging("imageURL");
                _imageURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imageURL");
                OnimageURLChanged();
            }
        }
        private global::System.String _imageURL;
        partial void OnimageURLChanging(global::System.String value);
        partial void OnimageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime startDate
        {
            get
            {
                return _startDate;
            }
            set
            {
                OnstartDateChanging(value);
                ReportPropertyChanging("startDate");
                _startDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startDate");
                OnstartDateChanged();
            }
        }
        private global::System.DateTime _startDate;
        partial void OnstartDateChanging(global::System.DateTime value);
        partial void OnstartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime endDate
        {
            get
            {
                return _endDate;
            }
            set
            {
                OnendDateChanging(value);
                ReportPropertyChanging("endDate");
                _endDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("endDate");
                OnendDateChanged();
            }
        }
        private global::System.DateTime _endDate;
        partial void OnendDateChanging(global::System.DateTime value);
        partial void OnendDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_DiscountInformation_Products", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_DiscountInformation_Products", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_DiscountInformation_Products", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_DiscountInformation_Products", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Sys_DBModel.FK_DiscountInformation_Products", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Fan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Fan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Fan object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="productID">Initial value of the productID property.</param>
        public static Fan CreateFan(global::System.Int32 id, global::System.Int32 productID)
        {
            Fan fan = new Fan();
            fan.id = id;
            fan.productID = productID;
            return fan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                OnproductIDChanging(value);
                ReportPropertyChanging("productID");
                _productID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productID");
                OnproductIDChanged();
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> speed
        {
            get
            {
                return _speed;
            }
            set
            {
                OnspeedChanging(value);
                ReportPropertyChanging("speed");
                _speed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("speed");
                OnspeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _speed;
        partial void OnspeedChanging(Nullable<global::System.Decimal> value);
        partial void OnspeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> weight
        {
            get
            {
                return _weight;
            }
            set
            {
                OnweightChanging(value);
                ReportPropertyChanging("weight");
                _weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("weight");
                OnweightChanged();
            }
        }
        private Nullable<global::System.Decimal> _weight;
        partial void OnweightChanging(Nullable<global::System.Decimal> value);
        partial void OnweightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> voltage
        {
            get
            {
                return _voltage;
            }
            set
            {
                OnvoltageChanging(value);
                ReportPropertyChanging("voltage");
                _voltage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("voltage");
                OnvoltageChanged();
            }
        }
        private Nullable<global::System.Int32> _voltage;
        partial void OnvoltageChanging(Nullable<global::System.Int32> value);
        partial void OnvoltageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> power
        {
            get
            {
                return _power;
            }
            set
            {
                OnpowerChanging(value);
                ReportPropertyChanging("power");
                _power = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("power");
                OnpowerChanged();
            }
        }
        private Nullable<global::System.Int32> _power;
        partial void OnpowerChanging(Nullable<global::System.Int32> value);
        partial void OnpowerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Fan_Products", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Fan_Products", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Fan_Products", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Fan_Products", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Sys_DBModel.FK_Fan_Products", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Food")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Food : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Food object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="productID">Initial value of the productID property.</param>
        public static Food CreateFood(global::System.Int32 id, global::System.Int32 productID)
        {
            Food food = new Food();
            food.id = id;
            food.productID = productID;
            return food;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ingredients
        {
            get
            {
                return _ingredients;
            }
            set
            {
                OningredientsChanging(value);
                ReportPropertyChanging("ingredients");
                _ingredients = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ingredients");
                OningredientsChanged();
            }
        }
        private global::System.String _ingredients;
        partial void OningredientsChanging(global::System.String value);
        partial void OningredientsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                OnproductIDChanging(value);
                ReportPropertyChanging("productID");
                _productID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productID");
                OnproductIDChanged();
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Food_Products", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Food_Products", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Food_Products", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Food_Products", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Sys_DBModel.FK_Food_Products", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of the productID property.</param>
        /// <param name="secCategoryID">Initial value of the secCategoryID property.</param>
        /// <param name="barCode">Initial value of the barCode property.</param>
        /// <param name="productName">Initial value of the productName property.</param>
        /// <param name="price">Initial value of the price property.</param>
        public static Product CreateProduct(global::System.Int32 productID, global::System.Int32 secCategoryID, global::System.String barCode, global::System.String productName, global::System.Decimal price)
        {
            Product product = new Product();
            product.productID = productID;
            product.secCategoryID = secCategoryID;
            product.barCode = barCode;
            product.productName = productName;
            product.price = price;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                if (_productID != value)
                {
                    OnproductIDChanging(value);
                    ReportPropertyChanging("productID");
                    _productID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("productID");
                    OnproductIDChanged();
                }
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 secCategoryID
        {
            get
            {
                return _secCategoryID;
            }
            set
            {
                OnsecCategoryIDChanging(value);
                ReportPropertyChanging("secCategoryID");
                _secCategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("secCategoryID");
                OnsecCategoryIDChanged();
            }
        }
        private global::System.Int32 _secCategoryID;
        partial void OnsecCategoryIDChanging(global::System.Int32 value);
        partial void OnsecCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String barCode
        {
            get
            {
                return _barCode;
            }
            set
            {
                OnbarCodeChanging(value);
                ReportPropertyChanging("barCode");
                _barCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("barCode");
                OnbarCodeChanged();
            }
        }
        private global::System.String _barCode;
        partial void OnbarCodeChanging(global::System.String value);
        partial void OnbarCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String productName
        {
            get
            {
                return _productName;
            }
            set
            {
                OnproductNameChanging(value);
                ReportPropertyChanging("productName");
                _productName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("productName");
                OnproductNameChanged();
            }
        }
        private global::System.String _productName;
        partial void OnproductNameChanging(global::System.String value);
        partial void OnproductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String brand
        {
            get
            {
                return _brand;
            }
            set
            {
                OnbrandChanging(value);
                ReportPropertyChanging("brand");
                _brand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("brand");
                OnbrandChanged();
            }
        }
        private global::System.String _brand;
        partial void OnbrandChanging(global::System.String value);
        partial void OnbrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> weight
        {
            get
            {
                return _weight;
            }
            set
            {
                OnweightChanging(value);
                ReportPropertyChanging("weight");
                _weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("weight");
                OnweightChanged();
            }
        }
        private Nullable<global::System.Decimal> _weight;
        partial void OnweightChanging(Nullable<global::System.Decimal> value);
        partial void OnweightChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_DiscountInformation_Products", "DiscountInformation")]
        public EntityCollection<DiscountInformation> DiscountInformations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DiscountInformation>("Sys_DBModel.FK_DiscountInformation_Products", "DiscountInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DiscountInformation>("Sys_DBModel.FK_DiscountInformation_Products", "DiscountInformation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Fan_Products", "Fan")]
        public EntityCollection<Fan> Fans
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Fan>("Sys_DBModel.FK_Fan_Products", "Fan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Fan>("Sys_DBModel.FK_Fan_Products", "Fan", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Food_Products", "Food")]
        public EntityCollection<Food> Foods
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Food>("Sys_DBModel.FK_Food_Products", "Food");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Food>("Sys_DBModel.FK_Food_Products", "Food", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Products_SecCategories", "SecCategories")]
        public SecCategory SecCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecCategory>("Sys_DBModel.FK_Products_SecCategories", "SecCategories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecCategory>("Sys_DBModel.FK_Products_SecCategories", "SecCategories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SecCategory> SecCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecCategory>("Sys_DBModel.FK_Products_SecCategories", "SecCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SecCategory>("Sys_DBModel.FK_Products_SecCategories", "SecCategories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Reviews_Products", "Reviews")]
        public EntityCollection<Review> Reviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Review>("Sys_DBModel.FK_Reviews_Products", "Reviews");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Review>("Sys_DBModel.FK_Reviews_Products", "Reviews", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_RiceCooker_Products", "RiceCooker")]
        public EntityCollection<RiceCooker> RiceCookers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RiceCooker>("Sys_DBModel.FK_RiceCooker_Products", "RiceCooker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RiceCooker>("Sys_DBModel.FK_RiceCooker_Products", "RiceCooker", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Review")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Review : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="reviewID">Initial value of the reviewID property.</param>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="productID">Initial value of the productID property.</param>
        /// <param name="comments">Initial value of the comments property.</param>
        /// <param name="rating">Initial value of the rating property.</param>
        public static Review CreateReview(global::System.Int32 reviewID, global::System.Int32 userID, global::System.Int32 productID, global::System.String comments, global::System.Int16 rating)
        {
            Review review = new Review();
            review.reviewID = reviewID;
            review.userID = userID;
            review.productID = productID;
            review.comments = comments;
            review.rating = rating;
            return review;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 reviewID
        {
            get
            {
                return _reviewID;
            }
            set
            {
                if (_reviewID != value)
                {
                    OnreviewIDChanging(value);
                    ReportPropertyChanging("reviewID");
                    _reviewID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("reviewID");
                    OnreviewIDChanged();
                }
            }
        }
        private global::System.Int32 _reviewID;
        partial void OnreviewIDChanging(global::System.Int32 value);
        partial void OnreviewIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                OnproductIDChanging(value);
                ReportPropertyChanging("productID");
                _productID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productID");
                OnproductIDChanged();
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comments
        {
            get
            {
                return _comments;
            }
            set
            {
                OncommentsChanging(value);
                ReportPropertyChanging("comments");
                _comments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comments");
                OncommentsChanged();
            }
        }
        private global::System.String _comments;
        partial void OncommentsChanging(global::System.String value);
        partial void OncommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 rating
        {
            get
            {
                return _rating;
            }
            set
            {
                OnratingChanging(value);
                ReportPropertyChanging("rating");
                _rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rating");
                OnratingChanged();
            }
        }
        private global::System.Int16 _rating;
        partial void OnratingChanging(global::System.Int16 value);
        partial void OnratingChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Reviews_Products", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Reviews_Products", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Reviews_Products", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_Reviews_Products", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Sys_DBModel.FK_Reviews_Products", "Products", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Reviews_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Reviews_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Reviews_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Reviews_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Sys_DBModel.FK_Reviews_Users", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="RiceCooker")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RiceCooker : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RiceCooker object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="productID">Initial value of the productID property.</param>
        public static RiceCooker CreateRiceCooker(global::System.Int32 id, global::System.Int32 productID)
        {
            RiceCooker riceCooker = new RiceCooker();
            riceCooker.id = id;
            riceCooker.productID = productID;
            return riceCooker;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                OnproductIDChanging(value);
                ReportPropertyChanging("productID");
                _productID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productID");
                OnproductIDChanged();
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> capacity
        {
            get
            {
                return _capacity;
            }
            set
            {
                OncapacityChanging(value);
                ReportPropertyChanging("capacity");
                _capacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("capacity");
                OncapacityChanged();
            }
        }
        private Nullable<global::System.Decimal> _capacity;
        partial void OncapacityChanging(Nullable<global::System.Decimal> value);
        partial void OncapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> power
        {
            get
            {
                return _power;
            }
            set
            {
                OnpowerChanging(value);
                ReportPropertyChanging("power");
                _power = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("power");
                OnpowerChanged();
            }
        }
        private Nullable<global::System.Int32> _power;
        partial void OnpowerChanging(Nullable<global::System.Int32> value);
        partial void OnpowerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> voltage
        {
            get
            {
                return _voltage;
            }
            set
            {
                OnvoltageChanging(value);
                ReportPropertyChanging("voltage");
                _voltage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("voltage");
                OnvoltageChanged();
            }
        }
        private Nullable<global::System.Int32> _voltage;
        partial void OnvoltageChanging(Nullable<global::System.Int32> value);
        partial void OnvoltageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_RiceCooker_Products", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_RiceCooker_Products", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_RiceCooker_Products", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Sys_DBModel.FK_RiceCooker_Products", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Sys_DBModel.FK_RiceCooker_Products", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="SecCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecCategory object.
        /// </summary>
        /// <param name="secCategoryID">Initial value of the SecCategoryID property.</param>
        /// <param name="categoryID">Initial value of the CategoryID property.</param>
        /// <param name="secCategoryTableName">Initial value of the SecCategoryTableName property.</param>
        /// <param name="secCategoryName">Initial value of the SecCategoryName property.</param>
        public static SecCategory CreateSecCategory(global::System.Int32 secCategoryID, global::System.Int32 categoryID, global::System.String secCategoryTableName, global::System.String secCategoryName)
        {
            SecCategory secCategory = new SecCategory();
            secCategory.SecCategoryID = secCategoryID;
            secCategory.CategoryID = categoryID;
            secCategory.SecCategoryTableName = secCategoryTableName;
            secCategory.SecCategoryName = secCategoryName;
            return secCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SecCategoryID
        {
            get
            {
                return _SecCategoryID;
            }
            set
            {
                if (_SecCategoryID != value)
                {
                    OnSecCategoryIDChanging(value);
                    ReportPropertyChanging("SecCategoryID");
                    _SecCategoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SecCategoryID");
                    OnSecCategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _SecCategoryID;
        partial void OnSecCategoryIDChanging(global::System.Int32 value);
        partial void OnSecCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                OnCategoryIDChanging(value);
                ReportPropertyChanging("CategoryID");
                _CategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryID");
                OnCategoryIDChanged();
            }
        }
        private global::System.Int32 _CategoryID;
        partial void OnCategoryIDChanging(global::System.Int32 value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecCategoryTableName
        {
            get
            {
                return _SecCategoryTableName;
            }
            set
            {
                OnSecCategoryTableNameChanging(value);
                ReportPropertyChanging("SecCategoryTableName");
                _SecCategoryTableName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecCategoryTableName");
                OnSecCategoryTableNameChanged();
            }
        }
        private global::System.String _SecCategoryTableName;
        partial void OnSecCategoryTableNameChanging(global::System.String value);
        partial void OnSecCategoryTableNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecCategoryName
        {
            get
            {
                return _SecCategoryName;
            }
            set
            {
                OnSecCategoryNameChanging(value);
                ReportPropertyChanging("SecCategoryName");
                _SecCategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecCategoryName");
                OnSecCategoryNameChanged();
            }
        }
        private global::System.String _SecCategoryName;
        partial void OnSecCategoryNameChanging(global::System.String value);
        partial void OnSecCategoryNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_SecCategories_Categories", "Categories")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Sys_DBModel.FK_SecCategories_Categories", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Sys_DBModel.FK_SecCategories_Categories", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Sys_DBModel.FK_SecCategories_Categories", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("Sys_DBModel.FK_SecCategories_Categories", "Categories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Products_SecCategories", "Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("Sys_DBModel.FK_Products_SecCategories", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("Sys_DBModel.FK_Products_SecCategories", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="Suggestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Suggestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Suggestion object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static Suggestion CreateSuggestion(global::System.Int32 id, global::System.String description, global::System.DateTime date)
        {
            Suggestion suggestion = new Suggestion();
            suggestion.id = id;
            suggestion.description = description;
            suggestion.date = date;
            return suggestion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userID;
        partial void OnuserIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Suggestions_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Suggestions_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Suggestions_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Sys_DBModel.FK_Suggestions_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Sys_DBModel.FK_Suggestions_Users", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Sys_DBModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="userName">Initial value of the userName property.</param>
        /// <param name="userPassword">Initial value of the userPassword property.</param>
        /// <param name="visitedTimes">Initial value of the visitedTimes property.</param>
        /// <param name="lastVisitedDate">Initial value of the lastVisitedDate property.</param>
        public static User CreateUser(global::System.Int32 userID, global::System.String userName, global::System.String userPassword, global::System.Int32 visitedTimes, global::System.DateTime lastVisitedDate)
        {
            User user = new User();
            user.userID = userID;
            user.userName = userName;
            user.userPassword = userPassword;
            user.visitedTimes = visitedTimes;
            user.lastVisitedDate = lastVisitedDate;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userPassword
        {
            get
            {
                return _userPassword;
            }
            set
            {
                OnuserPasswordChanging(value);
                ReportPropertyChanging("userPassword");
                _userPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userPassword");
                OnuserPasswordChanged();
            }
        }
        private global::System.String _userPassword;
        partial void OnuserPasswordChanging(global::System.String value);
        partial void OnuserPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private Nullable<global::System.Int16> _gender;
        partial void OngenderChanging(Nullable<global::System.Int16> value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 visitedTimes
        {
            get
            {
                return _visitedTimes;
            }
            set
            {
                OnvisitedTimesChanging(value);
                ReportPropertyChanging("visitedTimes");
                _visitedTimes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("visitedTimes");
                OnvisitedTimesChanged();
            }
        }
        private global::System.Int32 _visitedTimes;
        partial void OnvisitedTimesChanging(global::System.Int32 value);
        partial void OnvisitedTimesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime lastVisitedDate
        {
            get
            {
                return _lastVisitedDate;
            }
            set
            {
                OnlastVisitedDateChanging(value);
                ReportPropertyChanging("lastVisitedDate");
                _lastVisitedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastVisitedDate");
                OnlastVisitedDateChanged();
            }
        }
        private global::System.DateTime _lastVisitedDate;
        partial void OnlastVisitedDateChanging(global::System.DateTime value);
        partial void OnlastVisitedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Reviews_Users", "Reviews")]
        public EntityCollection<Review> Reviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Review>("Sys_DBModel.FK_Reviews_Users", "Reviews");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Review>("Sys_DBModel.FK_Reviews_Users", "Reviews", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Sys_DBModel", "FK_Suggestions_Users", "Suggestions")]
        public EntityCollection<Suggestion> Suggestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Suggestion>("Sys_DBModel.FK_Suggestions_Users", "Suggestions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Suggestion>("Sys_DBModel.FK_Suggestions_Users", "Suggestions", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
